### ISSUE TITLE
tsc -w无法运行

### ISSUE THREAD

**Issue by yanxiaodi** [f111fei/weapp-typescript#1]
按照说明下载后，运行tsc -w提示一下内容：

error TS5023: Unknown option 'w'
Use the '--help' flag to see options.
Version 1.0.3.0
Syntax:   tsc [options] [file ..]

Examples: tsc hello.ts
          tsc --out foo.js foo.ts
          tsc @args.txt

....

请问该如何解决？谢谢!

**Comment by f111fei** [comment]
抱歉，文档有误。 不是安装`tsc` 是安装 `typescript` 。 已经修改了文档。

**Comment by yanxiaodi** [comment]
多谢，我找到原因了，因为我之前在vs中装过旧版本的TypeScript，导致环境变量Path还是设置的旧版的，将环境变量手动改到新版就可以了。
请问微信的d.ts是手写的吗？如果以后微信有变化会随之更新吗？

**Comment by f111fei** [comment]
是手写的，这个项目会继续维护。官方更新API之后会同步一下。也欢迎提PR修正

**Comment by yanxiaodi** [comment]
感谢！我刚开始做小程序，有机会希望也能贡献点代码。

**Comment by yanxiaodi** [comment]
现在可以编译了，但运行报错：
jsEnginScriptError
Cannot set property data of #<IndexPage> which has only a getter
TypeError: Cannot set property data of #<IndexPage> which has only a getter

我看了一下IndexPageData属性是只有get，为何要这样设置呢？还请帮助解决一下，谢谢！

**Comment by f111fei** [comment]
应该是微信小程序的内核变动导致的不兼容， 已修复 https://github.com/f111fei/weapp-typescript/commit/cfd60c4ca3705ac315c319a1869344693888263c
